### ISSUE TITLE
Enable/Disable Wifi AP in lower android SDKs

### ISSUE THREAD

**Issue by DarthSid12** [florian-guillemard/WiFiFlutter#220]
So I see enabling/disabling Acess point in android is only for sdk 29 and above but using this stackoverflow answer https://stackoverflow.com/a/57368147/13858991 , I see its also possible for below sdk 26. I hope this feature can be added to allow for more reach of this package.

**Comment by daadu** [comment]
Just the answerer on SO - the plugin uses private Android APIs - you should be able to do it with this plugin.

Not sure where you saw the enable/disable is not supported. You can check [this table in readme](https://github.com/florian-guillemard/WiFiFlutter/tree/master/packages/wifi_iot#access-point).

**Comment by daadu** [comment]
Closing this, feel free to request re-opening.

**Comment by DarthSid12** [comment]
According to this table, enable/disable works for SDK 29 and above. I tried testing it on a lower SDK devices, namely 24 and 25 and 27 and it failed with the following error
```
E/class info.whitebyte.hotspotmanager.WifiApManager(29460): 
E/class info.whitebyte.hotspotmanager.WifiApManager(29460): java.lang.NoSuchMethodException: setWifiApEnabled [class android.net.wifi.WifiConfiguration, boolean]
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at java.lang.Class.getMethod(Class.java:2068)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at java.lang.Class.getMethod(Class.java:1690)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at info.whitebyte.hotspotmanager.WifiApManager.setWifiApEnabled(WifiApManager.java:80)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at com.alternadom.wifiiot.WifiIotPlugin.setWiFiAPEnabled(WifiIotPlugin.java:552)    
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at com.alternadom.wifiiot.WifiIotPlugin.onMethodCall(WifiIotPlugin.java:304)        
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at android.os.Handler.handleCallback(Handler.java:873)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at android.os.Handler.dispatchMessage(Handler.java:99)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at android.os.Looper.loop(Looper.java:201)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at android.app.ActivityThread.main(ActivityThread.java:6810)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at java.lang.reflect.Method.invoke(Native Method)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/class info.whitebyte.hotspotmanager.WifiApManager(29460):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
